version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - laravel
        

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER : root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  apache:
    image: php:8.2-apache
    container_name: laravel_apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge