name: CD

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no debian@51.75.21.202 'cd /var/www/html/nws && git config --global --add safe.directory /var/www/html/nws && sudo git pull origin release'
    - name: Install dependencies
      run: |
        ssh -o StrictHostKeyChecking=no debian@51.75.21.202 'cd /var/www/html/nws && sudo composer install && sudo npm install && sudo npm run build'
    - name: Caching
      run: |
        ssh -o StrictHostKeyChecking=no debian@51.75.21.202 'cd /var/www/html/nws && sudo php artisan config:cache && sudo php artisan route:cache && sudo php artisan view:cache'
    - name: Migrate database
      run: |
        ssh -o StrictHostKeyChecking=no debian@51.75.21.202 'cd /var/www/html/nws && sudo php artisan migrate --force'
