name: CD

on:
  pull_request:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no debian@51.75.21.202 'cd /var/www/html && sudo mkdir nws && cd nws && git init && git remote add origin https://github.com/wdhaghost/cicd.git && git pull origin release'
